import React,{useEffect,useRef,useState} from 'react';
import type {Project} from '../../../packages/core/src/model.js';
import {command,write} from './api.js';
import {DEFAULT_CONDITIONS,type PreviewConditions} from '../../../packages/core/src/workflow.js';

export function WorkflowPanel({project,selected,editorDirty,drafts,onDrafts,onClose,onCommit,onSeek}:{project:Project;selected:string;editorDirty:boolean;drafts:Record<string,string>;onDrafts:(v:Record<string,string>)=>void;onClose:()=>void;onCommit:(revision:number)=>Promise<void>;onSeek:(time:number)=>void}){
  const [tab,setTab]=useState('diagnosis'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<any>(null),[job,setJob]=useState<any>(null),[components,setComponents]=useState<any[]>([]),[reports,setReports]=useState<any[]>([]),[reviewed,setReviewed]=useState('');
  const state=useRef(drafts);state.current=drafts;
  const pending=Object.keys(drafts).length>0;
  const value=(key:string,fallback='')=>drafts[key]??fallback;
  const set=(key:string,v:string)=>{onDrafts({...state.current,[key]:v});setReviewed('');};
  const number=(key:string,fallback:number)=>Number(value(key,String(fallback)));
  const input=(label:string,key:string,fallback='',type='text')=><label>{label}<input type={type} value={value(key,fallback)} onChange={e=>set(key,e.target.value)}/></label>;
  const fieldSelect=(label:string,key:string,fallback:string,items:Array<[string,string]>)=><label>{label}<select value={value(key,fallback)} onChange={e=>set(key,e.target.value)}>{items.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>;
  async function run(op:string,input:any,mutates=false,review=false){
    setBusy(true);setError('');
    try{
      if(mutates&&editorDirty)throw new Error('Zapisz lub odrzuć szkic warstw przed zmianą zapisanej rewizji.');
      let key:string|undefined;
      if(mutates){const signature=JSON.stringify({op,input}),previous=state.current.__retry?JSON.parse(state.current.__retry):null;key=previous?.signature===signature?previous.key:crypto.randomUUID();onDrafts({...state.current,__retry:JSON.stringify({signature,key})});}
      const result=mutates?await write(op,input,key):await command(op,input);setResult(result);
      if(mutates){const remaining={...state.current};delete remaining.__retry;onDrafts(remaining);}
      if(review)setReviewed(JSON.stringify({op:op.replace(/\.preview$/,'.apply'),input}));
      if(result.type==='iteration.prepare')setJob(result);
      if(mutates&&result.revision&&result.projectId===project.id&&result.revision!==project.revision)await onCommit(result.revision);
      return result;
    }catch(e){setError(e instanceof Error?e.message:String(e));return null;}finally{setBusy(false);}
  }
  const cas={projectId:project.id,expectedRevision:project.revision};
  const applyButtons=(name:string,payload:any)=><div className="workflow-actions"><button disabled={busy} onClick={()=>void run(`${name}.preview`,payload,false,true)}>Pokaż zmianę</button><button disabled={busy||editorDirty||reviewed!==JSON.stringify({op:`${name}.apply`,input:payload})} onClick={()=>void run(`${name}.apply`,payload,true)}>Zastosuj zmianę</button></div>;
  const baseline={projectId:value('baseProject',project.document.authoring?.benchmark?.source.projectId??project.id),revision:number('baseRevision',project.document.authoring?.benchmark?.source.revision??project.revision)};
  const diagnostic={...baseline,observed:{projectId:project.id,revision:project.revision},layerId:value('diagnosticLayer',selected),mode:value('mode','compare'),groups:value('groups','texture,color,alpha,size').split(',').filter(Boolean),times:value('times',String(Math.min(.5,project.document.duration))).split(',').map(Number),binary:value('binary','true')==='true',render:true,conditions:project.document.authoring?.preview??DEFAULT_CONDITIONS};
  const saved=project.document.authoring?.preview,rigDefault=saved?.rig?(saved.rig.attachEffect?'attached':'reference'):'off';
  const cameraPreset=value('cameraPreset',saved?.camera?'saved':'near');
  const conditions:PreviewConditions={filtering:value('filtering',saved?.filtering??'export-mipmaps') as any,background:value('background',saved?.background??'dark') as any,
    camera:cameraPreset==='far'?{position:[7,-11,6],target:[0,0,.7],fov:39}:cameraPreset==='saved'&&saved?.camera?saved.camera:{position:[3.4,-5.4,2.75],target:[0,0,.7],fov:39},lightIntensity:number('lightIntensity',saved?.lightIntensity??1),
    ...(value('rig',rigDefault)==='off'?{}:{rig:{id:'schematic-human-v1',height:number('rigHeight',saved?.rig?.height??1.8),position:saved?.rig?.position??[0,0,0],yaw:number('rigYaw',saved?.rig?.yaw??0),velocity:[number('rigSpeed',saved?.rig?.velocity[0]??0),saved?.rig?.velocity[1]??0,saved?.rig?.velocity[2]??0],anchor:value('anchor',saved?.rig?.anchor??'impact') as any,attachEffect:value('rig',rigDefault)==='attached'}})};
  const concepts=project.document.authoring?.concepts??[];
  const settings={...cas,settings:{preview:conditions,concepts:value('conceptAsset')?[...concepts.filter(c=>c.assetId!==value('conceptAsset')),{assetId:value('conceptAsset'),name:value('conceptName','Koncept'),...(value('conceptMarker')?{markerId:value('conceptMarker')}:{})}]:concepts}};
  let timing:any,invalidTiming='';try{timing={...cas,period:number('period',project.document.duration),...(drafts.markers===undefined?{}:{markers:JSON.parse(drafts.markers)}),...(drafts.bindings===undefined?{}:{bindings:JSON.parse(drafts.bindings)})};}catch{invalidTiming='Nieprawidłowy JSON znaczników lub wiązań. Tekst pozostaje w formularzu.';}
  let markerRows:any[]=[],bindingRows:any[]=[];
  try{const ratio=number('period',project.document.duration)/project.document.duration;markerRows=drafts.markers===undefined?(project.document.authoring?.markers??[]).map(m=>({...m,time:m.time*ratio})):JSON.parse(drafts.markers);bindingRows=drafts.bindings===undefined?(project.document.authoring?.bindings??[]).map(b=>({...b,offset:b.offset*ratio})):JSON.parse(drafts.bindings);}catch{}
  const replaceRow=(key:string,rows:any[],index:number,patch:any)=>set(key,JSON.stringify(rows.map((r,i)=>i===index?{...r,...patch}:r),null,2));
  const chosenReport=reports.find(r=>r.id===value('reportId'));
  useEffect(()=>{
    if(!job||!['queued','running','cancelling'].includes(job.status))return;
    const timer=setInterval(()=>{void command('jobs.get',{jobId:job.id}).then(setJob).catch(e=>setError(e.message));},1500);return()=>clearInterval(timer);
  },[job?.id,job?.status]);
  return <div className="modal-backdrop"><section className="workflow-modal" role="dialog" aria-modal="true" aria-label="Praca nad iteracją">
    <header><div><span className="eyebrow">REWIZJA {project.revision}</span><h2>Praca nad iteracją</h2><p>{project.document.name}</p></div><button onClick={onClose}>Zamknij</button></header>
    <nav aria-label="Etapy pracy">{[['diagnosis','Porównanie'],['benchmark','Wzorzec'],['preview','Warunki i koncept'],['library','Biblioteka'],['timing','Zdarzenia i czas'],['reports','Raporty'],['job','Zadanie']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {editorDirty&&<p role="status">Edytor zawiera niezapisany szkic. Odczyty są dostępne; zapis zmian wymaga uporządkowania szkicu.</p>}
    {error&&<p className="workflow-error" role="alert">{error}</p>}
    <div className="workflow-body"><div className="workflow-form">
      {tab==='diagnosis'&&<><h3>Od wzorca do jednej zmiany</h3>{input('Projekt wzorca','baseProject',baseline.projectId)}{input('Rewizja wzorca','baseRevision',String(baseline.revision),'number')}
        {fieldSelect('Warstwa','diagnosticLayer',selected,project.document.layers.map(l=>[l.id,l.name]))}
        {fieldSelect('Rodzaj porównania','mode','compare',[['compare','Parametry bieżącej rewizji'],['white-control','Tylko biała tekstura'],['solo','Tylko wybrana warstwa'],['single','Bieżący wzorzec bez zmian']])}
        {input('Grupy: texture, color, alpha, size, count','groups','texture,color,alpha,size')}{input('Momenty podglądu [s], oddzielone przecinkami','times',String(Math.min(.5,project.document.duration)))}
        {fieldSelect('Format modelu','binary','true',[['true','Binarny — eksperymentalny'],['false','ASCII — eksperymentalny']])}
        <div className="workflow-actions"><button disabled={busy} onClick={()=>void run('workflow.compare',{projectId:project.id,revision:project.revision,baseline})}>Porównaj dane i eksport</button><button disabled={busy} onClick={()=>void run('workflow.analyze',{projectId:project.id,revision:project.revision})}>Analizuj bieżącą rewizję</button><button disabled={busy} onClick={()=>void run('diagnostics.plan',diagnostic,false,true)}>Pokaż plan wariantów</button><button disabled={busy||editorDirty} onClick={()=>void run('iteration.prepare',diagnostic,true).then(r=>{if(r)setTab('job');})}>Przygotuj paczkę iteracji</button></div><p>Każdy wariant zaczyna od tej samej rewizji. Ruch i dystans pozostają poza pierwszym porównaniem widoczności.</p></>}
      {tab==='benchmark'&&<><h3>Przypięty wynik</h3><p>{project.document.authoring?.benchmark?`Wzorzec: ${project.document.authoring.benchmark.source.projectId}, rewizja ${project.document.authoring.benchmark.source.revision}`:'Nie przypięto jeszcze wzorca.'}</p>
        {input('Projekt z raportem testu','reportsProject',project.id)}<button disabled={busy} onClick={()=>void run('reports.list',{projectId:value('reportsProject',project.id)}).then(r=>r&&setReports(r.detail.items))}>Pobierz raporty</button>
        {fieldSelect('Raport','reportId','',[['','Wybierz raport'],...reports.map(r=>[r.id,`${r.report.runner.name} · r${r.report.target.revision}`] as [string,string])])}
        {fieldSelect('Pozytywna obserwacja','observationId','',[['','Wybierz wynik'],...(chosenReport?.report.observations??[]).filter((o:any)=>o.result==='pass').map((o:any)=>[o.id,`${o.kind}: ${o.description}`])])}
        <button disabled={busy||editorDirty||!chosenReport||!value('observationId')} onClick={()=>void run('benchmarks.pin',{...cas,source:{projectId:chosenReport.report.target.projectId,revision:chosenReport.report.target.revision,snapshotSha256:chosenReport.report.target.snapshotSha256},reportId:chosenReport.id,observationId:value('observationId')},true)}>Przypnij ten wzorzec</button><p>Wynik dotyczy wskazanej wersji i warunków. Akceptację artystyczną zapisuje człowiek oddzielnie.</p></>}
      {tab==='preview'&&<><h3>Powtarzalne warunki podglądu</h3>{fieldSelect('Filtrowanie','filtering',conditions.filtering,[['export-mipmaps','Mipmapy — zgodnie z żądaniem eksportu'],['legacy-linear','Dawny podgląd bez mipmap']])}{fieldSelect('Tło','background',conditions.background,[['dark','Ciemne'],['light','Jasne'],['gray','Szare']])}{fieldSelect('Kamera','cameraPreset',saved?.camera?'saved':'near',[['saved','Zapisana'],['near','Blisko'],['far','Daleko']])}{input('Natężenie oświetlenia podglądu','lightIntensity',String(saved?.lightIntensity??1),'number')}
        {fieldSelect('Postać pomocnicza','rig',rigDefault,[['off','Wyłączona'],['reference','Widoczna jako odniesienie'],['attached','Efekt przy punkcie pomocniczym']])}{input('Wzrost [m]','rigHeight',String(saved?.rig?.height??1.8),'number')}{input('Obrót [rad]','rigYaw',String(saved?.rig?.yaw??0),'number')}{input('Ruch w osi X [m/s]','rigSpeed',String(saved?.rig?.velocity[0]??0),'number')}{fieldSelect('Punkt pomocniczy','anchor',saved?.rig?.anchor??'impact',[['origin','Początek'],['impact','Tułów'],['left-hand','Lewa dłoń'],['right-hand','Prawa dłoń']])}
        <p>Schemat postaci służy do pomiarów. Dłoń w podglądzie nie potwierdza obsługi dłoni jako celu EffectBeam. Fog, depth i pełna zgodność koloru z NWN pozostają niepotwierdzone.</p>
        <h3>Plansza konceptu</h3>{fieldSelect('Obraz z biblioteki PNG','conceptAsset','',[['','Bez nowego obrazu'],...(project.document.assets??[]).map(a=>[a.id,a.name] as [string,string])])}{input('Nazwa konceptu','conceptName','Koncept')}{fieldSelect('Faza konceptu','conceptMarker','',[['','Cały efekt'],...(project.document.authoring?.markers??[]).map(m=>[m.id,m.name] as [string,string])])}{applyButtons('workflow.settings',settings)}
        <div className="workflow-images">{concepts.map(c=>{const asset=project.document.assets?.find(a=>a.id===c.assetId);return asset&&<figure key={c.assetId}><img src={`data:image/png;base64,${asset.pngBase64}`} alt={c.name}/><figcaption>{c.name} · {c.assetId.slice(0,12)}{c.markerId&&` · ${c.markerId}`}</figcaption></figure>;})}</div></>}
      {tab==='library'&&<><h3>Niezmienne komponenty</h3><p>Publikowany jest wybór z tej rewizji, wraz z wymaganymi teksturami, dźwiękami i ograniczeniami.</p>{input('Nazwa komponentu','componentName',project.document.name)}<button disabled={busy||editorDirty} onClick={()=>void run('components.publish',{projectId:project.id,revision:project.revision,name:value('componentName',project.document.name),layerIds:project.document.layers.some(l=>l.id===selected)?[selected]:[],audioClipIds:project.document.audioClips?.some(c=>c.id===selected)?[selected]:[],limitations:['Zgodność należy ocenić w docelowej kompozycji.']},true)}>Opublikuj zaznaczoną część</button><button disabled={busy} onClick={()=>void run('components.list',{}).then(r=>r&&setComponents(r.detail.items))}>Odśwież bibliotekę</button>
        {fieldSelect('Komponent','componentId','',[['','Wybierz komponent'],...components.map(c=>[c.id,`${c.name} · r${c.source.revision}`] as [string,string])])}{input('Prefiks nowych warstw','prefix','part')}{applyButtons('components.insert',{...cas,componentId:value('componentId'),prefix:value('prefix','part')})}</>}
      {tab==='timing'&&<><h3>Znaczniki i harmonogram</h3>{input('Długość efektu / okres [s]','period',String(project.document.duration),'number')}
        <p>Zmiana okresu przelicza czas animacji i zdarzeń. Początek klipu może się przesunąć; bajty WAV, jego offset, długość i wysokość dźwięku pozostają bez zmian.</p>
        {!invalidTiming&&<><div className="workflow-marker-rows">{markerRows.map((m,i)=><div key={i}><label>Nazwa fazy<input value={m.name} onChange={e=>replaceRow('markers',markerRows,i,{name:e.target.value})}/></label><label>Czas fazy [s]<input type="number" step="0.01" value={m.time} onChange={e=>replaceRow('markers',markerRows,i,{time:Number(e.target.value)})}/></label><small>{m.id}</small><button onClick={()=>{onDrafts({...state.current,markers:JSON.stringify(markerRows.filter((_,j)=>j!==i)),bindings:JSON.stringify(bindingRows.filter(b=>b.markerId!==m.id))});setReviewed('');}}>Usuń fazę i jej wiązania</button></div>)}</div><button onClick={()=>set('markers',JSON.stringify([...markerRows,{id:'phase-'+crypto.randomUUID().slice(0,8),name:'Nowa faza',time:0}]))}>Dodaj fazę</button>
        {bindingRows.map((b,i)=><div key={i}><label>Warstwa lub dźwięk<select value={b.targetType+':'+b.targetId} onChange={e=>{const [targetType,targetId]=e.target.value.split(':');replaceRow('bindings',bindingRows,i,{targetType,targetId});}}>{[...project.document.layers.map(l=>({value:'layer:'+l.id,label:l.name})),...(project.document.audioClips??[]).map(c=>({value:'audio:'+c.id,label:c.name}))].map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></label><label>Faza<select value={b.markerId} onChange={e=>replaceRow('bindings',bindingRows,i,{markerId:e.target.value})}>{markerRows.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Przesunięcie [s]<input type="number" step="0.01" value={b.offset} onChange={e=>replaceRow('bindings',bindingRows,i,{offset:Number(e.target.value)})}/></label><button onClick={()=>set('bindings',JSON.stringify(bindingRows.filter((_,j)=>j!==i)))}>Usuń wiązanie</button></div>)}<button disabled={!markerRows.length} onClick={()=>set('bindings',JSON.stringify([...bindingRows,{targetType:project.document.audioClips?.length?'audio':'layer',targetId:project.document.audioClips?.[0]?.id??project.document.layers[0].id,markerId:markerRows[0].id,offset:0}]))}>Powiąż początek z fazą</button></>}
        <details><summary>Zaawansowany zapis znaczników i wiązań</summary>
        <label>Znaczniki — id, name, time [s]<textarea value={value('markers',JSON.stringify(project.document.authoring?.markers??[],null,2))} onChange={e=>set('markers',e.target.value)} placeholder={'[{"id":"down","name":"Ruch w dół","time":1}]'}/></label>
        <label>Wiązania początku — targetType, targetId, markerId, offset [s]<textarea value={value('bindings',JSON.stringify(project.document.authoring?.bindings??[],null,2))} onChange={e=>set('bindings',e.target.value)} placeholder={'[{"targetType":"audio","targetId":"down","markerId":"down","offset":0}]'}/></label>
        </details>{invalidTiming?<p role="alert">{invalidTiming}</p>:applyButtons('timing',timing)}
        <div className="workflow-actions">{(project.document.authoring?.markers??[]).map(m=><button key={m.id} onClick={()=>onSeek(m.time)}>{m.name} · {m.time}s</button>)}</div></>}
      {tab==='reports'&&<><h3>Wynik zewnętrznego testu</h3><p>Import sprawdza tożsamość kandydata. Nagrania oraz pliki instalacji pozostają deklaracją odbiorcy; Studio nie uruchamia gry ani nie przyznaje akceptacji artystycznej.</p><label>Wczytaj raport JSON<input type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];if(file){if(file.size>262144){setError('Raport przekracza256KiB.');return;}void file.text().then(text=>set('reportJson',text));}}}/></label><label>Treść raportu<textarea value={value('reportJson')} onChange={e=>set('reportJson',e.target.value)}/></label>
        <button disabled={busy||!value('reportJson')} onClick={()=>{try{const report=JSON.parse(value('reportJson'));void run('reports.import',{projectId:report.target.projectId,report},true);}catch{setError('Raport nie jest poprawnym JSON.');}}}>Importuj raport z hashami</button><button disabled={busy} onClick={()=>void run('reports.list',{projectId:project.id}).then(r=>r&&setReports(r.detail.items))}>Wyniki tej kompozycji</button>
        {reports.map(r=><article key={r.id}><strong>{r.report.runner.name} · rewizja {r.report.target.revision}</strong><ul>{r.report.observations.map((o:any)=><li key={o.id}>{o.kind} · {o.result}: {o.description}</li>)}</ul><small>Dowody zewnętrzne · {r.report.target.snapshotSha256.slice(0,12)}</small></article>)}</>}
      {tab==='job'&&<><h3>Etapy iteracji</h3>{input('Identyfikator zadania','jobId',job?.id??'')}<button disabled={busy} onClick={()=>void run('jobs.get',{jobId:value('jobId',job?.id??'')}).then(r=>r&&setJob(r))}>Odczytaj zadanie</button>{job&&<><p><strong>{job.status}</strong> · {job.id}</p>{job.error&&<p role="alert">{job.error.message}</p>}<table><thead><tr><th>Etap</th><th>Stan</th><th>Czas</th></tr></thead><tbody>{job.metadata?.stages?.map((s:any)=><tr key={s.key}><td>{s.key}</td><td>{s.status}{s.reused?' · wznowiony wynik':''}</td><td>{Math.round(s.milliseconds)}ms</td></tr>)}</tbody></table><div className="workflow-actions"><button disabled={busy||!['queued','running'].includes(job.status)} onClick={()=>void run('jobs.cancel',{jobId:job.id},true).then(r=>r&&setJob(r))}>Anuluj zadanie</button><button disabled={busy||!['failed','blocked','cancelled'].includes(job.status)} onClick={()=>void run('jobs.resume',{jobId:job.id},true).then(r=>r&&setJob(r))}>Wznów od ukończonych etapów</button></div><ul>{job.artifacts?.map((a:any)=><li key={a.id}><a href={a.downloadUrl} download={a.name}>{a.name}</a> · {a.size}B · {a.sha256.slice(0,12)}</li>)}</ul><div className="workflow-images">{job.artifacts?.filter((a:any)=>a.mime==='image/png').map((a:any)=><figure key={a.id}><img src={a.downloadUrl} alt={a.name}/><figcaption>{a.name}</figcaption></figure>)}</div></>}</>}
    </div><aside className="workflow-result"><h3>Wynik operacji</h3>{result?<WorkflowResult value={result}/>:<p>Wybierz porównanie, analizę lub podgląd zmiany.</p>}</aside></div>
    <footer><span>{pending?'Pola formularza pozostają zachowane także po zamknięciu.':'Wspólne operacje UI, CLI i WebMCP.'}</span><button disabled={busy||!pending} onClick={()=>{onDrafts({});setReviewed('');}}>Wyczyść formularz</button></footer>
  </section></div>;
}
function WorkflowResult({value}:{value:any}){
  const detail=value.detail??value,layers=detail.authored?.layers??detail.diff?.layers,findings=detail.findings;
  return <><p>{value.kind??value.type??'Wynik'}{value.revision&&` · rewizja ${value.revision}`}</p>{layers&&<table><thead><tr><th>Warstwa</th><th>Zmiana</th></tr></thead><tbody>{layers.map((l:any)=><tr key={l.id}><td>{l.id}</td><td>{l.status}{l.behavior?.map((d:any)=><div key={d.path}>{d.path}: {JSON.stringify(d.before)?.slice(0,90)} → {JSON.stringify(d.after)?.slice(0,90)}</div>)}</td></tr>)}</tbody></table>}{findings&&<ul>{findings.map((f:any,i:number)=><li key={i}><strong>{f.severity}</strong>: {f.message}</li>)}</ul>}{detail.variants&&<ul>{detail.variants.map((v:any)=><li key={v.id}><strong>{v.id}</strong>: {v.hypothesis}<br/>{v.allowedFields.join(', ')||'Bez zmiany parametrów'}</li>)}</ul>}{detail.schedule&&<ul>{detail.schedule.map((e:any,i:number)=><li key={i}>{e.targetId} → {e.markerId}: {e.time}s, okres {e.repeatPeriod??'brak'}s</li>)}</ul>}<details><summary>Dane pomiarowe i tożsamości</summary><pre>{JSON.stringify(detail,null,2).slice(0,160000)}</pre></details></>;
}
