import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const root=resolve('output/iteration-lab/2026-09-10/qualified'),out=join(root,'wings-acceptance');await mkdir(out,{recursive:true});
const h=JSON.parse(await readFile(join(root,'handoff.json'),'utf8')),config=join(root,'tlc-import-agent.config.json'),run=promisify(execFile);
const call=async(args:string[])=>{const r=JSON.parse((await run(process.execPath,[h.cli,'--config',config,'--json',...args],{maxBuffer:40*1024*1024})).stdout);if(r.status==='failed')throw Error(JSON.stringify(r.error));return r.data;};
const op=async(name:string,input:any,key?:string)=>{const path=join(out,`${name.replaceAll('.','-')}-${key??'preview'}.json`);await writeFile(path,JSON.stringify(input));return call([...name.split('.'),'--input-file',path,...(key?['--idempotency-key',key]:[])]);};
const path='C:/Projects/the last city/assets/vfx/wampir/skrzydla/source/audio/master-minus16-v1/candidate/effect-document.json',originalBytes=await readFile(path),original=JSON.parse(originalBytes.toString()),sha=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
const compact=join(out,'source-compact.json');await writeFile(compact,JSON.stringify(original));
const imported=await call(['projects','import','--file',compact,'--project','studio-028-wings-source-check','--idempotency-key','studio-028-wings-import']);
const oldClip=original.audioClips.find((c:any)=>c.id==='cloth-downstroke');assert(oldClip);assert.equal(original.duration,1.4);
const marked=await op('timing.apply',{projectId:imported.id,expectedRevision:1,markers:[{id:'downstroke',name:'Downstroke',time:oldClip.start}],bindings:[{targetType:'audio',targetId:oldClip.id,markerId:'downstroke',offset:0}]},'studio-028-wings-marker');
const timing={projectId:imported.id,expectedRevision:marked.revision,period:1.6},current=await call(['projects','inspect','--project',imported.id]),preview=await op('timing.preview',{...timing,expectedRevision:current.revision});assert.equal(preview.detail.audioBytesUnchanged,true);
const applied=await op('timing.apply',timing,'studio-028-wings-retime');
const saved=await call(['projects','inspect','--project',imported.id]),d=saved.document;assert.deepEqual(d.audioAssets,original.audioAssets);
const clip=d.audioClips.find((c:any)=>c.id===oldClip.id);assert(Math.abs(clip.start-oldClip.start*1.6/1.4)<1e-9);assert.deepEqual({...clip,start:oldClip.start},oldClip);
for(const [i,layer] of d.layers.entries()){assert.deepEqual(layer.geometry,original.layers[i].geometry);for(const [track,keys] of Object.entries(original.layers[i].animation) as any)for(const [k,key] of keys.entries()){const actual=layer.animation[track][k];assert(Math.abs(actual.time-key.time*1.6/1.4)<1e-8);assert.deepEqual({...actual,time:key.time},key);}}
const component=await op('components.publish',{projectId:imported.id,revision:saved.revision,name:'Qualified left wing and downstroke',layerIds:['left'],audioClipIds:[oldClip.id],limitations:['Isolated authoring acceptance; no native/art approval.']},'studio-028-wings-publish');
const reference={id:'existing-reference',name:'Existing reference',type:'mesh',enabled:true,color:'#ffffff',alpha:1,start:0,duration:1.6,position:[0,0,0],orientation:[0,0,1,0],scale:1,geometry:{kind:'box',dimensions:[.1,.1,.1]},animation:{}};
const empty={...original,name:'Component copy fixture',duration:1.6,layers:[reference],assets:[],audioAssets:[],audioClips:[],locks:[]};const emptyPath=join(out,'target.json');await writeFile(emptyPath,JSON.stringify(empty));
const target=await call(['projects','import','--file',emptyPath,'--project','studio-028-wings-component-check','--idempotency-key','studio-028-wings-target-v2']);
const insertion={projectId:target.id,expectedRevision:1,componentId:component.detail.component.id,prefix:'copy'};await op('components.insert.preview',insertion);await op('components.insert.apply',insertion,'studio-028-wings-insert');
const copied=(await call(['projects','inspect','--project',target.id])).document;assert.equal(copied.layers.length,2);assert.deepEqual(copied.layers[0],reference);assert.deepEqual(copied.layers.find((l:any)=>l.id==='copy-left').geometry,d.layers.find((l:any)=>l.id==='left').geometry);assert.equal(copied.audioAssets.length,1);assert.deepEqual(copied.audioAssets[0],original.audioAssets.find((a:any)=>a.id===oldClip.assetId));assert.equal(copied.authoring.bindings[0].markerId,'copy-phase-downstroke');
assert.deepEqual((await call(['projects','inspect','--project',imported.id])).document,d);assert.equal(sha(await readFile(path)),sha(originalBytes));
const result={status:'passed',source:path,sourceFileSha256:sha(originalBytes),sourceUnchanged:true,projectId:imported.id,revision:applied.revision,periodBefore:1.4,periodAfter:d.duration,clipStartBefore:oldClip.start,clipStartAfter:clip.start,geometryAndKeyValuesUnchanged:true,audioBytesAndTrimUnchanged:true,componentId:component.detail.component.id,targetProjectId:target.id,requiredAudioAssetsCopied:1,originalAudioAssets:original.audioAssets.length,nativeTested:false};
await writeFile(join(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
