import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { build } from 'esbuild';
import { operationSchemas, validateResult } from '../packages/contracts/src/schema.js';
import { WEBMCP_OPERATIONS, webMCPInputSchemas } from '../apps/web/src/webmcp-schemas.js';

const root = fileURLToPath(new URL('../', import.meta.url));
const target = resolve(root, 'apps/web/src/generated/webmcp-contracts.ts');
const inputSchemas = webMCPInputSchemas(operationSchemas);
const ajv = new Ajv({ allErrors: true, strict: false, allowUnionTypes: true, inlineRefs: false, code: { source: true, esm: true } });
const exports: Record<string, string> = {}, inputNames: Record<string, string> = {}, outputNames: Record<string, string> = {};
function add(name: string, schema: object) {
  const id = `https://nwn-vfx.local/browser-validators/${name}`;
  ajv.addSchema(schema, id); exports[name] = id;
}
add('validateResult', validateResult.schema as object);
for (const [index, [name, schema]] of Object.entries(inputSchemas).entries()) {
  const exported = `input${index}`; add(exported, schema); inputNames[name] = exported;
}
for (const [index, name] of WEBMCP_OPERATIONS.entries()) {
  const exported = `output${index}`; add(exported, operationSchemas[name].outputSchema); outputNames[name] = exported;
}
const standalone = standaloneCode(ajv, exports);
// Standalone AJV references small runtime helpers via require(). Bundle these
// statically for the browser; schema compilation and Function stay build-only.
const bundled = await build({ stdin: { contents: standalone, resolveDir: root, sourcefile: 'webmcp-validators.generated.js' },
  bundle: true, write: false, format: 'esm', platform: 'browser', target: 'es2023', legalComments: 'none', minifyWhitespace: true });
const code = bundled.outputFiles[0].text;
if (/\bnew\s+Function\s*\(|\beval\s*\(|\bFunction\s*\(/.test(code)) throw new Error('Generated browser validators contain dynamic code evaluation.');
const metadata = Object.fromEntries(WEBMCP_OPERATIONS.map(name => {
  const { description, inputSchema, mutates } = operationSchemas[name];
  return [name, { description, inputSchema, mutates }];
}));
const validatorType = 'type BrowserValidator = ((value: unknown) => boolean) & { errors?: unknown };\n';
const map = (name: string, entries: Record<string, string>) => `export const ${name}: Record<string, BrowserValidator> = {${Object.entries(entries).map(([key, value]) => `${JSON.stringify(key)}:${value}`).join(',')}};\n`;
const source = '// @ts-nocheck\n// Generated by npm run generate:browser-contracts. Do not edit. No runtime compilation.\n' +
  code + '\n' + validatorType + map('inputValidators', inputNames) + map('outputValidators', outputNames) +
  `export const operationSchemas: Record<string,{description:string;inputSchema:object;mutates:boolean}> = ${JSON.stringify(metadata)};\n` +
  `export const inputSchemas: Record<string,object> = ${JSON.stringify(inputSchemas)};\n`;
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== source) throw new Error('Generated browser contracts are stale. Run npm run generate:browser-contracts.');
  process.stdout.write('Browser contracts match the canonical schemas.\n');
} else {
  mkdirSync(dirname(target), { recursive: true }); writeFileSync(target, source);
  process.stdout.write(`Generated ${Object.keys(inputNames).length} tool input and ${Object.keys(outputNames).length} shared output validators.\n`);
}
